name: Deploy Web Content

on: 
  push:
    branches:
      - main
  # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  deploy:    
    name: "main branch" 
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Checking out repo code onto ubuntu runner"
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo "Deploying code onto server"
      - name: "Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: "134.122.122.126"
          remote-user: "github"
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          remote-path: "/var/www/fishmantutoring.com"
      
